### ISSUE TITLE
Stored variables {{---}} not getting used when book is built

### ISSUE THREAD

**Issue by eeholmes** [snowex-hackweek/website2022#20]
Thus they are appearing like `{{github_org_url}}` in this page for example:

https://icesat-2.hackweek.io/preliminary/git.html

and others.

**Comment by jomey** [comment]
Closing this in favor of the linked issue with the main template.
Substitutions within a code block are not supported and this was the root cause for this issue.
See the [MyST Docs](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#substitutions-with-jinja2)
