### ISSUE TITLE
bad merge of Megan and Zach's bios

### ISSUE THREAD

**Issue by hpmarshall** [snowex-hackweek/website2022#32]
Well, I reviewed approved @meganmason 's pull request for her bio and that went great!  Then I moved on to @ZachKeskinen 's pull request for his bio, which didn't have Megan's bio.  I tried to resolve merge conflicts, by copy/paste to make one team file that had both Megan and Zach, trying to be very careful with indentation.  I failed to preview the result, and committed the merge.  It failed the "buildresources" test.  Somehow it doesn't seem like it broke the website, which is looking like it did before this merge? @scottyhq ?

**Comment by jomey** [comment]
The PR #28 was closed and not merged. Hence we are still missing Zack.

@ZachKeskinen - Can you open a fresh PR to get your profile onto the site?

**Comment by hpmarshall** [comment]
Thanks @jomey .  I'm still a bit confused why when I merged and committed this (accidentally), it didn't propagate the changes to team.yaml.  Is it because it didn't pass the required buildresources?

When editing a conflicted file as part of a merge on github browser, is there an easy way to see the preview before committing? 

And I guess better practice, rather than merging, would be to ask Zach to pull the most recent, checkout a new branch, add bio and then pull request again? Thanks!

**Comment by jomey** [comment]
> Thanks @jomey . I'm still a bit confused why when I merged and committed this (accidentally), it didn't propagate the changes to team.yaml. Is it because it didn't pass the required buildresources?
> 
My current reconstruction of the sequences are this:
* Zach opened the PR and it was flagged as not being up to date with the SnowEx `main` branch
* You merged the latest SnowEx `main` branch into [Zach`s main](https://github.com/ZachKeskinen/website2022). See the [history of Zach’s fork](https://github.com/ZachKeskinen/website2022/commits/main)
* The PR was then closed by Zach

So all the changes from this PR, including your merge of main, are still on Zach’s fork of the website and never got merged to this website.

Does that help to understand which changes are currently where?


> When editing a conflicted file as part of a merge on github browser, is there an easy way to see the preview before committing?

I personally find it hard to resolve issues on the GitHub UI and usually do this locally on my computer. There you can preview your merge results and build the website before actually committing.
The steps you described to resolve this look correct to me. Probably would have done something very similar to what you did.

> And I guess better practice, rather than merging, would be to ask Zach to pull the most recent, checkout a new branch, add bio and then pull request again? Thanks!

Yup. I think it is a common practice to ask the author of a PR to resolve any merge conflicts for an open PR. You can always give it your best shot and as soon as things get more spicy, ask the author for their assistance.

**Comment by hpmarshall** [comment]
Thanks so much @jomey , now that makes good sense.  I couldn't figure out why things were showing up on Zach's fork.  I'll stick with working locally on my computer, seems a bit more straightforward.
